[package]
authors = ["ichyo"]
edition = "2018"
name = "nes"
version = "0.1.0"
[dependencies]
env_logger = "0.6.1"
image = "0.21.0"
lazy_static = "1.3.0"
log = "0.4.6"
portaudio = "*"
sdl2 = "0.32.1"

[profile.release]
debug = true
